# RR configuration version
version: '3'

# rpc:
#   listen: tcp://127.0.0.1:6001

# server:
#   command: "/app/worker.php"
#   relay: "pipes"

# http:
#   address: "0.0.0.0:3000"

# logs:
#   level: development
